const department = [
    "Aerospace Studies",
    "Afro-American Studies",
    "African Languages and Literature",
    "Agricultural and Applied Economics",
    "Agricultural and Life Sciences",
    "Anthropology",
    "Animal Sciences",
    "Art",
    "Art History",
    "Astronomy",
    "Bacteriology",
    "Biochemistry",
    "Biological Systems Engineering",
    "Biomolecular Chemistry",
    "Biophysics",
    "Biostatistics and Medical Informatics",
    "Botany",
    "Business",
    "Cell and Regenerative Biology",
    "Chemical and Biological Engineering",
    "Chemistry",
    "Classics,Comparative Literature",
    "Clinical Pharmacology",
    "Community and Environmental Sociology",
    "Communication Arts",
    "Computer Sciences",
    "Consumer Science",
    "Counseling Psychology",
    "Curriculum and Instruction",
    "Cytotechnology",
    "Dance",
    "Data Science",
    "Design Studies",
    "East Asian Languages and Literature",
    "Economics",
    "Educational Leadership Policy Analysis",
    "Educational Policy Studies",
    "Electrical and Computer Engineering",
    "Entomology",
    "Environmental Services",
    "Family Medicine and Community Health",
    "Food Science",
    "Forest and Wildlife Ecology",
    "French and Italian,German",
    "Geography",
    "Geoscience",
    "Human Oncology",
    "Industrial and Systems Engineering",
    "Integrative Biology",
    "Landscape Architecture",
    "Law",
    "Life Sciences Communication",
    "Mathematics",
    "Mechanical Engineering",
    "Medical Genetics",
    "Medical Microbiology and Immunology",
    "Medicine",
    "Military Science",
    "Music",
    "Naval Science",
    "Neuroscience",
    "Nursing",
    "Nutritional Sciences",
    "Pharmacy",
    "Philosophy",
    "Physics",
    "Plant Pathology",
    "Political Science",
    "Population Health Sciences",
    "Psychology",
    "Rehabilitation Psychology and Special Education",
    "Sociology",
    "Space Science and Engineering",
    "Strategic Communication",
    "Surgery",
    "Sustainability and the Global Environment",
    "Theatre and Drama",
    "Urban and Regional Planning"
  ];
  
  export default department;
  